version: "3.8"

services:
  app:
    build: .
    ports:
      - "${PORT:-7000}:7000"
    environment:
      - PORT=7000
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    depends_on:
      - redis
      - postgres
    volumes:
      - ./src:/app/src
      - ./uploads:/app/uploads

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
